### ISSUE TITLE
Support a queue for people waiting for a wing

### ISSUE THREAD

**Issue by laneatomic** [small-worlds/discordbot#1]
We would like the ability for a user to request a wing, so whoever is winging people into a jump point can work off of a queue. We also need a way for whoever is winging to get the next name in the queue, clear a name from the queue, and see how many people are waiting for a wing. We don't necessarily care about data persistence, so in-memory should be fine.

**Comment by laneatomic** [comment]
Per discussion with Nuse, we also want to be able to tie this in to a web interface so whoever is running the wing can easily see a list of members, click on "claim next" (or something like that), and move the queue along. Nuse does not want to have to interact with a bot due to the speed of which things go.

**Comment by ravstar52** [comment]
Close issue?

**Comment by ravstar52** [comment]
Closing, Think we have this working. Think
