### ISSUE TITLE
Trading tool for commodities

### ISSUE THREAD

**Issue by ravstar52** [small-worlds/discordbot#29]
commodity trading tool.
ie, I have 5 modular terminals on hand.

PersonA wants to see what rare commodities someone has had in past 24 hours.
type in command

list
XCNuse: 5 modular terminals, 2 lavian brandy
Virtual Anomaly: 2 biowaste, 4 nanobreakers
Jerek: 1 Platinum, 1 Telemetry Suite(edited)
from there, personA can say... hey @XCNuse, do you still have the modular terminals?
and if so they can be shared
the only thing about this though is everyone needs to be on top of their list.

maybe even have it so the "database" is zeroed out 24 hours after you say you have a commodity

**Comment by ravstar52** [comment]
no longer required? @laneatomic since engineers don't need them.

**Comment by laneatomic** [comment]
Burn it down 🔥
